; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:24s]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
lib_deps =
	;adafruit/Adafruit GFX Library @ ^1.11.11
	;adafruit/Adafruit ILI9341 @ ^1.6.1
	;z3t0/IRremote @ ^4.7.1
	;Encoder

upload_speed = 921600

build_type = debug

build_flags =
    -DCONFIG_DEVICE_ID=\"24S-HUB-001\"
    -DCONFIG_MQTT_BROKER_URI=\"mqtt://YOUR_BROKER:1883\"

board_build.mcu = esp32s2
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_upload.flash_size = 4MB

monitor_filters =
    esp32_exception_decoder

lib_ldf_mode = chain+